### ISSUE TITLE
Application Registration - Happy Path

### ISSUE THREAD

**Issue by SkyHustle** [Dmitry1007/traffic_spy#2]
- As a user
- When I send a Post request to: http://yourapplication:port/sources
  parameters 'identifier=jumpstartlab&rootUrl=http://jumpstartlab.com
- Then I expect a 200 response with data as JSON {"identifier":"jumpstartlab"}

**Comment by maxtedford** [comment]
You can use ActiveRecord's validation feature for this: http://guides.rubyonrails.org/active_record_validations.html
